### ISSUE TITLE
Definition of force_ssl on the REST Shop Object triggers deprecated API call warning on installed apps using this package

### ISSUE THREAD

**Issue by tchillingworth** [osiset/Basic-Shopify-API#118]
The 2021-07 Shopify API release deprecated the force_ssl field on the REST Shop resource. Release notes here: [https://shopify.dev/api/release-notes/2021-07](url) 

I found the force_ssl property defined in the following file:
vendor\osiset\basic-shopify-api\test\fixtures\rest\admin__shop.json

I believe all that needs to be done is to remove the force_ssl property from the shop json, as it is no longer being used.

**Comment by osiset** [comment]
@tchillingworth That is a fixure used for tests. Its a response from Shopify. I have removed it in master, thanks.
