### ISSUE TITLE
RateLimiter blowing up after change

### ISSUE THREAD

**Issue by mddickens** [osiset/Basic-Shopify-API#121]
The change that was made yesterday to RateLimiter is blowing things up:

[2021-09-04 18:28:20] production.ERROR: Trying to access array offset on value of type float {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type float at /var/www/html/pc-app/vendor/osiset/basic-shopify-api/src/Middleware/RateLimiting.php:59)

I reverted that function back to the previous version and it's working again.

**Comment by elachino** [comment]
Hi i resolved it changed temporary the code adding this: 

Before (line 59)

` $firstTime = end($times)['time'];`

After

` if (is_array($times)) {
            if (is_array(end($times))) {
                $firstTime = end($times)['time'];
            }
            if(!is_array(end($times))) {
                $firstTime = end($times);
            }
        }
        if (!is_array($times)) {
            $firstTime = $times;
        }`

I suppose this error was caused by shopify api version used.

**Comment by roberttolton** [comment]
This is odd, because that data should be an array, as set here:

https://github.com/osiset/Basic-Shopify-API/blob/a83e66891511535ea338e67281892d6e8289a320/src/Middleware/UpdateApiLimits.php#L106:L111

I'll put together a Pull Request for this.

**Comment by roberttolton** [comment]
Think I found the culprit, the `UpdateRequestTime` Middleware.

@osiset Whats the purpose of mixing the storage array with arrays and floats? I think this middleware should just be deleted as the time is now being added into the array that’s pushed, alongside the call totals per request.

**Comment by osiset** [comment]
@roberttolton Your PR has been approved, can you confirm the rate limiter is working as expected now with your change?

**Comment by roberttolton** [comment]
@osiset Have been running it for a few hours now, pulling ~10,000 records off Shopify with no errors yet.

**Comment by osiset** [comment]
Thanks ill push a patch.
