### ISSUE TITLE
PHP 8.1 Warnings

### ISSUE THREAD

**Issue by asacarter** [osiset/Basic-Shopify-API#132]
Deprecated: Return type of Osiset\BasicShopifyAPI\ResponseAccess::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in \vendor\osiset\basic-shopify-api\src\Osiset\BasicShopifyAPI\ResponseAccess.php on line 60

Deprecated: Return type of Osiset\BasicShopifyAPI\ResponseAccess::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in \vendor\osiset\basic-shopify-api\src\ResponseAccess.php on line 156

#[\ReturnTypeWillChange] can be used to suppress the warning.

**Comment by JoshHighland** [comment]
I'm having the same issue.

**Comment by JoshHighland** [comment]
Looks like https://github.com/osiset/Basic-Shopify-API/pull/129 solves this. Once it's merged
