### ISSUE TITLE
API Rate Limiting

### ISSUE THREAD

**Issue by kneeki** [osiset/Basic-Shopify-API#52]
I'm finding that whatever settings I enter into `$this->api->enableRateLimiting(750, 500);` doesn't seem to be working, or I'm misunderstanding something. To test it, I've created a function:
```php
public function testDelay() {
    for ($i = 1; $i <= 5; $i++) {
        $job = new DelayTest($i, new DateTime('now'));
        $this->dispatch($job);
    }
    echo "\n";
}
```

The job being executed reaches out to Shopify and pulls an index on orders from another controller. Here's the Job:
```php
class DelayTest implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    private $iteration;
    private $then;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(int $iteration, DateTime $then)
    {
        $this->iteration = $iteration;
        $this->then = $then;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        $now = new DateTime('now');
        $getCtrl = new GetController();
        $orders = $getCtrl->orders('1', (string)$this->iteration, '10', 'any', 'any', 'any');
        $orders = \json_decode($orders);
        echo $this->iteration . '| order id: ' . $orders[0]->id . " then: " . $this->then->format('H:i:s:v') . ", now: " . $now->format('H:i:s:v') . "\n";
    }
}
```
The output of the above gives me this:
```
1| order id: 1874921488420 then: 06:51:16:114, now: 06:51:16:118
2| order id: 1874915131428 then: 06:51:16:652, now: 06:51:16:653
3| order id: 1874907103268 then: 06:51:17:121, now: 06:51:17:122
4| order id: 1874894946340 then: 06:51:17:642, now: 06:51:17:643
5| order id: 1874877317156 then: 06:51:18:095, now: 06:51:18:096
```

What confuses me is that the now: timestamp isn't being incremented by 750ms. Am I approaching this correctly?

**Comment by ohmybrew** [comment]
@kneeki The rate limiting is not for (your code), its the rate limiting support for Shopify API calls.

The package implements a very simple version of this, you're allowed to hit Shopify's API twice in one second for regular shops, or four times in one second for Plus shops.

Whats the limiter does, is it checks the header returned by Shopify. The header contains how many calls you used and have left. If you run out of calls, the library will sleep until it can gain calls back.

Does that help?

**Comment by kneeki** [comment]
So, theoretically even this basic version of a rate limiter should prevent
the 429 error, right? Or does it not queue up commands and just sleeps the
one request?

**Comment by ohmybrew** [comment]
It calculates a wait time and sleeps.

**Comment by amosmos** [comment]
Hey,

Two quick questions regarding the conversation in this issue:

1) You mention the limiter checks the header returned by Shopify, but in the code it seems it just keeps the timestamp of the last request it issued, and calculate the sleep time based on that, so not real check based on the Shopify header - am I missing something?

2) If I didn't miss anything, that means the limiter only "knows" about recent requests made by itself, so in the case of the OP, when the requests are made by separate jobs, the limiter will not know about the other requests - am I right or wrong?
Of course if I'm wrong in question #1 and the limiter does check the header by Shopify, it will support rate limiting requests from separate jobs, so I hope I am wrong :-)

Thanks!
Amos

**Comment by osiset** [comment]
The header value is used to know what's left. The timestamps are used to make sure not too many calls are happening. But yes, multiple instances would cause an issue since it's not a static value.. I would need to implement it as a static value but I believe there were issues with opcache at the time when I attempted it..

Either way it's meant to be basic, someone can implement their own if they really need to, I'll of course improve on it when I can.
________________________________

**Comment by amosmos** [comment]
Thanks!

It makes perfect sense.

So would you recommend to check if a request had a rate limit issue and in that case use the getApiCalls function to check when run it again?
I can assume this function can be the basis for an internal mechanism that will automatically run the call again until a different response is sent (I think there's a different issue for that which you said you might work on in the future).

Also, I'm not an expert on static values so correct me if I'm wrong, but I believe that won't help in case of async queue jobs calling the api.

THANKS!
Amos
