### ISSUE TITLE
Async with GraphQL

### ISSUE THREAD

**Issue by sltwtr-apps** [osiset/Basic-Shopify-API#53]
I see rest has async, what about GraphQL?   Is anything prohibitive to implementing this?

**Comment by ptcampbell** [comment]
https://github.com/ohmybrew/Basic-Shopify-API#graphql

**Comment by sltwtr-apps** [comment]
@ptcampbell I don't see anything mentioning sync requests.   Rest has async https://github.com/ohmybrew/Basic-Shopify-API#rest-async

**Comment by ohmybrew** [comment]
@sltwtr-apps I have not yet got around to doing the async stuff for GraphQL, I will try to tackle this tonight!

**Comment by osiset** [comment]
Available in 7.0.0 to be released tonight.
