### ISSUE TITLE
"access_scopes" gets no token attached

### ISSUE THREAD

**Issue by tzookb** [osiset/Basic-Shopify-API#63]
## Expected Behavior

When requesting to get the current token `access_scopes`
I would like to get them properly

## Current Behavior

Currently I get a 401 response, thats because we are not adding the access token to the request.

### Steps to Reproduce

1. do a GET request to `/admin/oauth/access_scopes`
2. you will get 401

I looked a the code and saw the below method inside `BasicShopifyAPI.php`
We are not adding the token for the "access_scopes" path

Any reason for that?

```php
    protected function isAuthableRequest(string $uri)
    {
        return preg_match('/\/admin\/oauth\/(authorize|access_token|access_scopes)/', $uri) === 0;
    }
```

Thanks!

**Comment by osiset** [comment]
@tzookb Found the issue, fixed in master, will be releasing 7.0.0 tonight which will cover it.

![2020-03-17_14-53](https://user-images.githubusercontent.com/2420282/76883578-59714a00-685f-11ea-9928-14f9bf821279.png)
