### ISSUE TITLE
Missing Headers in Error Response?

### ISSUE THREAD

**Issue by jason-engage** [osiset/Basic-Shopify-API#64]
Hi, why not return the Headers in rest error response?

**Comment by osiset** [comment]
I can add the original response object from Guzzle to the error object if thats what you mean.

**Comment by jason-engage** [comment]
Yeah that would be cool, like in the success object, 'resp' - more symmetrical that way

**Comment by osiset** [comment]
v8.1.0 now has response in error callback. Reopen if theres an issue.
