### ISSUE TITLE
Change Connection Timeout?

### ISSUE THREAD

**Issue by jason-engage** [osiset/Basic-Shopify-API#65]
Hi, where would you update the guzzle 'connect_timeout' => X value in the code?

I think at the moment its set to a large default number...

**Comment by osiset** [comment]
Hey, currently I set nothing.

![2020-04-01_21-14](https://user-images.githubusercontent.com/2420282/78196702-c854c280-745d-11ea-90c5-956fd1ee6a91.png)

Just pushed a commit to allow you to pass in additional parameters to the Guzzle client via the constructor... will release shortly.

**Comment by osiset** [comment]
v8.1.0 has option for passing additional headers in creation. Reopen if theres an issue.

**Comment by jason-engage** [comment]
Cheers, thanks for the updates!
