### ISSUE TITLE
Return value of Osiset\BasicShopifyAPI::jsonDecode() must be an instance of stdClass, null returned

### ISSUE THREAD

**Issue by ianfortier** [osiset/Basic-Shopify-API#67]
Catch this in my Sentry logs, sometimes Shopify seems to return null.
Maybe can we add something to catch the null in `$this->jsonDecode($body);`

```
Symfony\Component\Debug\Exception\FatalThrowableError: Return value of Osiset\BasicShopifyAPI::jsonDecode() must be an instance of stdClass, null returned
#19 /vendor/osiset/basic-shopify-api/src/Osiset/BasicShopifyAPI.php(1004): Osiset\BasicShopifyAPI::jsonDecode
#18 /vendor/osiset/basic-shopify-api/src/Osiset/BasicShopifyAPI.php(832): Osiset\BasicShopifyAPI::Osiset\{closure}
#17 /vendor/osiset/basic-shopify-api/src/Osiset/BasicShopifyAPI.php(868): Osiset\BasicShopifyAPI::rest
```

**Comment by osiset** [comment]
@ianfortier Which osiset/basic-shopify-api version are you on? Check with composer info.
I recently released a new version last week and it doesn't have a type return because it could be stdClass or array now, previously it was just stdClass.

**Comment by ianfortier** [comment]
"osiset/basic-shopify-api": "^8.1"

Will try to update to 8.2

**Comment by khiconit** [comment]
Why you are return array instead stdClass ? @osiset 

`[
            'errors'     => false,
            'response'   => $resp,
            'status'     => $resp->getStatusCode(),
            'body'       => $this->toResponse($resp->getBody()),
            'link'       => $link,
            'timestamps' => $this->getTimeStore()->get($this->getSession()),
        ]` 

I like stdClass more than array
LOL
:D

**Comment by osiset** [comment]
@khiconit It was changed because there was several people using this package with my other repository (laravel-shopify) and trying to map the responses to a Laravel JSON Resource, this is not possible with a stdClass.

The main return of rest/graph will return an array now instead of stdClass. However, the "body" of the response can be accessed as an array or stdClass.

Will close for now unless present in 8.2+.
