### ISSUE TITLE
More examples needed for `graphAsync`

### ISSUE THREAD

**Issue by zoltan-patchworks** [osiset/Basic-Shopify-API#70]
I'm trying to use the `grapAsync` function and in the `then` handler calling the Laravel `Log::debug` function, but it does not seem to log anything to the logfile.

Could you please add some working examples to the readme?

Thanks

**Comment by osiset** [comment]
If you're running async you need to wait or settle it. Check out the Guzzle docs on how to handle async.

```php
$api->graphAsync('{ shop { name } }')->then(function () {
    echo "Hello!";
})->wait();
```

Will produce "Hello!" in your terminal before the script ends.
