### ISSUE TITLE
Different error response structure

### ISSUE THREAD

**Issue by awebartisan** [osiset/Basic-Shopify-API#71]
Sometimes errors are returned in different structure from Shopify API.

I am making a call to Fulfillment endpoint.

This is the error response I am getting:

![image](https://user-images.githubusercontent.com/29105478/85195038-b9591000-b2e8-11ea-85d6-8309c569d48c.png)
With "base" property.

While some errors are returning a generic structure:
![image](https://user-images.githubusercontent.com/29105478/85195101-27053c00-b2e9-11ea-956f-3b1c33b3c7c7.png)

Therefore, accessing error message in first case like: `$response['body']` throws an error.

**Comment by osiset** [comment]
The errors property returns the exact structure from Shopify. In your case, the errors in both are correct, as that is the error returned by Shopify for fulfillment issue, the "base" and other sub properties are direct from Shopify.

@awebartisan

**Comment by awebartisan** [comment]
Normally we access error as `$response['body']`, but in second case it throws error because its not a string its an array.

So should we always check `is_string` or `is_array` before accessing `$response['body']` if `errors` is `true` ?

**Comment by osiset** [comment]
@awebartisan Checking...

So on failure:

```php
                // Convert data to response
                $body = $this->toResponse($rawBody);
                $body = $body->hasErrors() ? $body->getErrors() : null;
```

Which leads to:

```
    /**
     * Get the errors.
     *
     * @return mixed
     */
    public function getErrors()
    {
        if (!$this->hasErrors()) {
            return;
        }

        return isset($this->container['errors']) ? $this->container['errors'] : $this->container['error'];
    }
```

I guess it depends, yes. If "error" or "errors" is a string, then you will get that back, if its an array, it will be an array. I am not modifying the data returned from Shopify in this case.

In your generic structure example, it would return a string. In your first example, it would be an array with `base` as the first key.

So yeah, is_array should work!

**Comment by awebartisan** [comment]
Thanks Tyler!
