### ISSUE TITLE
GraphQL Storefront API

### ISSUE THREAD

**Issue by sltwtr-apps** [osiset/Basic-Shopify-API#72]
I duplicated function graph and called the new function storefront.  Then in storefront I changed this:

$this->versionPath('/admin/api/graphql.json')

To this:

$this->versionPath('/api/graphql')

Why wouldn't that work?  Anyone have any luck with this?

**Comment by osiset** [comment]
Storefront requires header work and other items, its not supported by this library right now but I may add it in the future.
