### ISSUE TITLE
REST response is always an object after 9.1.1

### ISSUE THREAD

**Issue by Wise-Gorilla** [osiset/Basic-Shopify-API#74]
Hello @osiset ,
after version 9.0.0 and before 9.1.1 $products_call is used t be an array but on 9.1.1 i see it's object, is that on purpose or it's bug because i don't see that mentioned on UPGRADING.md and if it's on purpose then how can i get it as an array?

            $query = $this->shopify->rest('GET', '/admin/products.json', $param);
            $products_call = $query['body']['products'];

**Comment by osiset** [comment]
Not a mistake. Everything returns an instance of ResponseAccess. Its a class which allows you to access the response easier (can be accessed via array or object, easier to grab the errors etc.

It implements array abilities so you can do this just fine:

```php
print count($query['body']['products']) . PHP_EOL;
foreach ($query['body']['products'] as $product) {
    print_r($product->id);
    print PHP_EOL;
    // or
    print_r($product['id']);
}
```

**Comment by Wise-Gorilla** [comment]
Thanks @osiset , What i find it abit strange is that on version 9.0.0 and 9.1.0 the following code was working fine

        $since_id = 0;
        $products = array();
        while ($since_id !== null) {
            $param = [
                'fields'   => 'id,title',
                'limit'    => 250,
                'since_id' => $since_id
            ];
            $query = $this->shopify->rest('GET', '/admin/products.json', $param);

            $products_call = $query['body']['products'];

            $since_id = end($products_call)['id'] ?? null;
            if ($products_call) {
                $products = array_merge($products, $products_call);
            }
        }

However on version 9.1.1 i started to get an array_merge error because $products_call is an object not an array... well the solusion i found is to do type casting like that which was not required on 9.1.0
$products_call = (array) $query['body']['products'];

So im wondering if that breaking change made on purpose on 9.1.1? and if so do you think that the way im doing to do the merge by doing type casting is the right way?

**Comment by osiset** [comment]
@Wise-Gorilla 9.0.0 had a bug inside, an array was supposed to return a new instance of ResponseAccess, which is why it "worked" before because it was a raw array.

What I can do is add an toArray method which you can use, like: $query['body']['products']->toArray(), you can then use this in array_merge.
