### ISSUE TITLE
Bump Guzzle to ^6.5|^7.0

### ISSUE THREAD

**Issue by securit** [osiset/Basic-Shopify-API#82]
Can you please bump your guzzle in composer.json to 
```
"guzzlehttp/guzzle":"^6.5|^7.0"
```

thanks

**Comment by jedimdan** [comment]
I just started a new project with Laravel 8 and wanted to use this package but can't also due to this package requiring Guzzle 6 as well.

But if it helps, I can do a PR for this :)

**Comment by adddz** [comment]
Please update the package to support Laravel 8. Thank you.

**Comment by securit** [comment]
Thats the purpose of this PR
