### ISSUE TITLE
Timeout not handled

### ISSUE THREAD

**Issue by numerogeek** [osiset/Basic-Shopify-API#85]
Hello, 

I have an issue when the Shopify API doesn't respond within 10 seconds. 
The response object is entirely null. 

Here: https://github.com/osiset/Basic-Shopify-API/blob/master/src/Osiset/BasicShopifyAPI/Clients/Rest.php#L186
In case of timeout, the $resp is empty, so everything is null.

You can reproduce the problem by setting a very low timeout options in your client.

**Comment by osiset** [comment]
You're saying its timing out and not giving you a failure response? If its returning the response, you can access the excpetion.

**Comment by osiset** [comment]
Closing for stale, reopen if you have an answer to above :)
