### ISSUE TITLE
Call to a member function api()

### ISSUE THREAD

**Issue by sandeeppangeni** [osiset/Basic-Shopify-API#86]
I am trying to create a order outside the app. I want to create an api to make order from shopify frontend. 
`

> <?php
>      namespace App\Http\Controllers;
> 
> 	use Illuminate\Http\Request;
> 	use OhMyBrew\BasicShopifyAPI;
> 	use OhMyBrew\ShopifyApp\Facades\ShopifyApp;
> 	use App\User;
> 	use OhMyBrew\ShopifyApp\Models\Shop;
> 	use View;
> 	
> 	use Illuminate\Support\Facades\DB;
> 	use Illuminate\Support\Facades\Schema;
> 	use App\Support\Collection;
> 
> 	class ShopController extends Controller
> 	{
> public function makeorder(Request $request){
> 	      $responsedata= $request->all();
> 	      //let we have all order data in $order
> 	      $order = array("order"=>$line_items);
> 	      $shop = ShopifyApp::shop();
> 	        $domain =  $shop->shopify_domain;	            
> 	        $accesstoken = $shop->shopify_token;
> 
> 	        $api = new BasicShopifyAPI();
> 	        $api->setVersion('2020-01'); // "YYYY-MM" or "unstable"	
> 	        $api->setShop($domain);
> 	        $api->setAccessToken($accesstoken); 
> 	        $shop_data = $shop->api()->rest('POST', '/admin/api/2020-07/orders.json', $order);
> 		 return json_encode($shop_data);
> 
> 
> 	  }
> 	  }

`

**Comment by osiset** [comment]
Please use the template and format code properly.

**Comment by sandeeppangeni** [comment]
I want to create an order from shopify frontend.
I want to use app as an API . Is it possible ? If yes, how ??
