### ISSUE TITLE
How to handle expired sessions

### ISSUE THREAD

**Issue by axelf** [osiset/Basic-Shopify-API#87]
@osiset Hi,

where does `$_SESSION['shop']` come from? What if the session is expired? How can i handle this in my app?

**Comment by osiset** [comment]
What is the context? I don't use session object.

**Comment by axelf** [comment]
In the documentation under "Getting Access" i saw this session variable

**Comment by osiset** [comment]
That's just example code, nothing to do with the library. It can be handled any way you see fit.

**Comment by axelf** [comment]
Ok, thank you.
