### ISSUE TITLE
Retry on 200 status for GraphQL

### ISSUE THREAD

**Issue by sudo-rm-rf-star** [osiset/Basic-Shopify-API#95]
Hi, 

Status codes within GraphQL responses are usually 200, even when something goes wrong. The default retry strategy by setting `retry_on_status` does not work as we only want to retry on the responses with status code 200 where something actually went wrong. 

For example, I'd like to have a retry strategy when I have a `Throttled` error message within my GraphQL response. Is this possible? 

Thanks in advance!

**Comment by osiset** [comment]
Everything is Guzzle-based middleware. You can remove the internal retry middleware and develop your own...

```php
$api->removeMiddleware('request:retry');
$api->addMiddleware(yourmiddleware);
```

**Comment by sudo-rm-rf-star** [comment]
Okay, thanks!
